03/04 Note Below

In [9]:
2 + 2

4

In [6]:
3 + 3

6

In [7]:
4 + 4

8

In [10]:
print ("hello")

hello


In [1]:
3 != 3

False

In [2]:
spring_cups = 2

In [3]:
spring_cups

2

In [10]:
spring_total = spring_cups + 5

In [5]:
spring_total

7

In [6]:
spring_cups = 4

In [8]:
spring_cups

4

In [11]:
spring_total

9

In [15]:
spring_cups += 5

In [13]:
spring_cups

9

In [14]:
spring_cups

9

In [16]:
spring_cups

14

In [17]:
spring_cups

14

In [18]:
(1000000 + 2000000)

3000000

In [19]:
(1000000 + 
 2000000)

3000000

In [20]:
type (4.5)

float

In [21]:
round (2/3)

1

In [22]:
help (type)

Help on class type in module builtins:

class type(object)
 |  type(object) -> the object's type
 |  type(name, bases, dict, **kwds) -> a new type
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __dir__(self, /)
 |      Specialized __dir__ implementation for types.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __instancecheck__(self, instance, /)
 |      Check if an object is an instance.
 |  
 |  __or__(self, value, /)
 |      Return self|value.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __ror__(self, value, /)
 |      Return value|self.
 |  
 |  __setattr__(self, name, value, /)
 |      Implement setattr(self, name, value).
 |  
 |  __sizeof__(self, /)
 |      Return mem

In [23]:
round (2/3, 4)

0.6667

In [24]:
print (round (abs(-16) * 1.5))

24


In [26]:
def c_to_f (degree_c):
    degree_f = (9/5)* degree_c + 32
    return degree_f

In [27]:
c_to_f (100)

212.0

In [28]:
c_to_f (-22)

-7.600000000000001

In [32]:
def divide(dividend, divisor):
    output = dividend / divisor
    return output

In [33]:
divide (100, 5)

20.0

In [37]:
def calc_sales_tax (price, tax_rate=0.13):
    tax_amt = price * tax_rate
    return tax_amt

In [39]:
calc_sales_tax(15)

1.9500000000000002

In [40]:
calc_sales_tax(15, 0.08)

1.2

In [42]:
15 * 0.08

1.2

In [43]:
def calc_total_bill (price, tax_rate=0.13, tip_rate=0.15):
    tax_amt = price * tax_rate
    tip_amt = price * tip_rate
    return price + tax_amt + tip_amt

In [45]:
calc_total_bill

<function __main__.calc_total_bill(price, tax_rate=0.13, tip_rate=0.15)>

In [46]:
calc_total_bill (100)

128.0

In [48]:
calc_total_bill(100, tip_rate=0.18)

131.0

In [49]:
help (c_to_f)

Help on function c_to_f in module __main__:

c_to_f(degree_c)



In [ ]:
def c_to_f (degree_c):
    """covert degrees from Celsius to Fahrenheit"""
    # dog string with three quotation marks
    return ((9/5) * degree_c +32)

In [51]:
help (c_to_f)

Help on function c_to_f in module __main__:

c_to_f(degree_c)
    covert degrees from Celsius to Fahrenheit



03/09/2026 Note below

In [1]:
"This is a string"

'This is a string'

In [2]:
'This is also a string'
# it is does not matter single or double quotation mark but needs to be consistent

'This is also a string'

In [3]:
"""This
is
a
multiline
string"""

'This\nis\na\nmultiline\nstring'

In [ ]:
# Escape Consequences
# \r move the cursor back to the beginning of the current line and overwrite them
print ("1234\r567")

5674


In [7]:
print ("adbdefg")

adbdefg


In [8]:
print ("abcdef\rg")

gbcdef


In [10]:
"Hello" + "my" + "cat"

'Hellomycat'

In [11]:
"ha" * 3

'hahaha'

In [ ]:
"The year is" + 2020
# mix them is not allowed

TypeError: can only concatenate str (not "int") to str

In [14]:
"The year is" + "2026"

'The year is2026'

In [15]:
"apple" == "Apple"

False

In [16]:
first_name = "Ada"

In [17]:
last_name = "Lovelace"

In [18]:
first_name

'Ada'

In [19]:
last_name

'Lovelace'

In [ ]:
first_name[0]
# first letter position is the index 0 and second one is index 1...

'A'

In [22]:
last_name[3]

'e'

In [ ]:
last_name[2:5]
# first index to the n+1 - give you index 2,3,4

'vel'

In [ ]:
last_name[4:]
# if no ending index provided, it will go all the way to the end

'lace'

In [ ]:
# slice the third-to-last character
last_name[-3]

'a'

In [28]:
last_name[-3:]

'ace'

In [29]:
phone_number = "+1 555-124-4567"

In [31]:
phone_number

'+1 555-124-4567'

In [32]:
phone_number[3:6]

'555'

In [33]:
print (1, "fish", 2, "fish")

1 fish 2 fish


In [ ]:
# Len is a build-in function tells you how many characters in the sentence
len("we have a very very very long sentence and need to know how many characters there are")

85

In [36]:
fruit = "banana"
fruit

'banana'

In [37]:
sorted (fruit)

['a', 'a', 'a', 'b', 'n', 'n']

In [ ]:
"I am not yelling" .upper()

'I AM NOT YELLING'

In [39]:
"This string is unusual".count("e")

0

In [40]:
"file_name.csv".endswith(".csv")

True

In [41]:
"long file name with space.csv".replace(" ", "_")

'long_file_name_with_space.csv'

In [ ]:
# format function of string
"Ada Lovelace\'s initials are {} . {}. " .format(first_name[0], last_name[0])

"Ada Lovelace's initials are A . L. "

In [43]:
"My favourate vegetable is {}" .format("potato")

'My favourate vegetable is potato'

In [47]:
# f-string
f"Ada Lovelace's initial are {first_name[0]}. {last_name[0]}."

"Ada Lovelace's initial are A. L."

In [49]:
f"My favourate vegetable is {'potato'}"

'My favourate vegetable is potato'

In [ ]:
# change float to int
int(17.4)

17

In [ ]:
# change strting to int. only works if the string is an int itself
int("18")

18

In [52]:
type (int("18"))

int

In [ ]:
# String -> float
float ('892')

892.0

In [54]:
# float -> String
str (37.6)

'37.6'

In [55]:
type (str (37.6))

str

In [ ]:
#  if you want the user to enter something you use an input function
age = input("how old are you?")

In [57]:
age

'1000'

In [58]:
color = input ("what is your fav color?")

In [59]:
color

'pink'

In [60]:
animal = input ("what is your fav animal?")

In [61]:
animal

''

In [62]:
age_next_bday = int(age) +1
age_next_bday

1001

In [ ]:
#control float 
#not - logic operator not a function
# negate the truth value of the statement
not True

False

In [65]:
not False

True

In [ ]:
not (3 == 3)

False

In [68]:
print (not True)

False


In [69]:
# and: check if the statement on both sides are true
True and False


False

In [70]:
(7 == 7) and (9 > 32) # True and False

False

In [ ]:
# behaviour of the and operator is that is will return the first 
# flasy value encountered or the last truthy vlause if all operands 
# are ture based on the conditions provided
is_winter = "True" # string, non-empty and is considered "True"
is_cloudy = True #boolean
is_winter and is_cloudy #"True" and True

True

In [72]:
is_cloudy and is_winter # True and "True"

'True'

In [73]:
"" and False #empty String and booleean False

''

In [74]:
False and ""

False

In [75]:
0 and 1 #0 is interpreted as False in python and 1 is true

0

In [76]:
(4 == 4) or False

True

In [77]:
not (7 % 2 ==1) or False

False

In [79]:
# or operator return the first truthy value encountered or the last falsy
# value if all operands are "False"
True or "True"

True

In [80]:
"True" or True

'True'

In [81]:
0 or 0

0

In [82]:
0 or " "

' '

In [83]:
year = 2026
if year >= 2000:
    print ("We are in the 21st century.")

We are in the 21st century.


In [84]:
year = 1994
if year >= 2000:
    print ("We are in the 21st century.")

In [85]:
breakfast_eaten = "no"
if breakfast_eaten == "yes":
    print ("Good job!")

In [86]:
breakfast_eaten = "yes"
if breakfast_eaten == "yes":
    print ("Good job!")

Good job!


In [87]:
year = 1994
if year >= 2000:
    print ("We are in the 21st century.")
else:
    print ("We are not in the 21 century.")

We are not in the 21 century.


In [88]:
year = 1867
if year >= 2000:
    print ("We are in the 21st century.")
elif year >= 1900:
    print ("We are in the 20th century.")
elif year >=1800:
    print ("We are in the 19th century.")
else:
    print ("We are way back in time!")

We are in the 19th century.


In [90]:
year = 2026
if year >= 2000:
    print ("We are in the 21st century.")
elif year >= 1900:
    print ("We are in the 20th century.")
elif year >=1800:
    print ("We are in the 19th century.")
else:
    print ("We are way back in time!")

We are in the 21st century.


In [ ]:
year = 2026
if year >= 2000:
    print ("We are in the 21st century.")
if year >= 1900:
    print ("We are in the 20th century.")
if year >=1800:
    print ("We are in the 19th century.")
else:
    print ("We are way back in time!")

We are in the 21st century.
We are in the 20th century.
We are in the 19th century.


03/11/2026 Note Below

In [1]:
day_of_week = "Thursday"

if (day_of_week == "Saturday") or (day_of_week == "Sunday"):
    print ("Weekend")
else:
    print ("Weekday")

Weekday


In [6]:
def eye_exam_covered(age, qualifying_condition, time_since_last_exam):
    '''assume (1) age is paased as an int is for the age of a person 
    (2) qualifying_condition is passed as a bool (True/False) 
    indiciating whether a eligible medical condition is met, 
    and (3) tune_since_last_exam is passed as int for 
    the number of months since the last eye exam'''
    if 0 <= age <= 19:
        if time_since_last_exam >= 12:
            return "You are eligible for one major eye exam and any minor assessment."
        else:
            return "It hasn't been 12 months since your last major eye exam."
    elif 20<= age <=64:
        if qualifying_condition: #if qualifying_condition == True is also fine but just better to leave it blank
            if time_since_last_exam >=12:
                return "You are eligibale for 1 major eye exam and and two additional follow-up minor assessment."
            else:
                return "It hasn't been 12 months since your last major eye exam."
        else:
            return "You do not have a qualifying eligible medical condition."
    elif age >= 65:
        if time_since_last_exam >= 18:
            return "You are eligibale for 1 major eye exam and and two additional follow-up minor assessment."
        else:
            return "It hasn't been 12 months since your last major eye exam."
    else:
        return "Invalid age input"

In [4]:
eye_exam_covered (19, False, 11)

"It hasn't been 12 months since your last major eye exam."

In [5]:
eye_exam_covered(27, True, 15)

'You are eligibale for 1 major eye exam and and two additional follow-up minor assessment.'

In [7]:
eye_exam_covered(-10, True, 15)

'Invalid age input'

In [8]:
# lists
# []
vowels = ["a","e","i","o","u"]

In [9]:
vowels

['a', 'e', 'i', 'o', 'u']

In [10]:
empty_list = []

In [11]:
empty_list

[]

In [12]:
empty_list2 = list ()

In [13]:
empty_list2

[]

In [16]:
scores = [90, 80, 82, 91, 80]

In [17]:
scores

[90, 80, 82, 91, 80]

In [18]:
grades = ["K", 1, 2, 3, 4, 5]

In [19]:
grades

['K', 1, 2, 3, 4, 5]

In [21]:
mystery_solvers = [
    ["Sherlock", "Watson"], 
    ["Scooby", "Shaggy"],
    "Nancy"
]

In [22]:
mystery_solvers

[['Sherlock', 'Watson'], ['Scooby', 'Shaggy'], 'Nancy']

In [23]:
# ordered: each item in a list can be referenced by its index (or position) in the list
grades [0]

'K'

In [26]:
# how do you call an item from a list within another list?
mystery_solvers [0][0]

'Sherlock'

In [27]:
# lists are mutable
# modified in place
# strings, ints, floats -> immutable
# cannot be changed
# when we update an immutable data type we replace the value entirely

perfect_sqaure = [1, 4, 9, 16, 25, 37, 49]
perfect_sqaure

[1, 4, 9, 16, 25, 37, 49]

In [29]:
perfect_sqaure [5] = 36
perfect_sqaure

[1, 4, 9, 16, 25, 36, 49]

In [33]:
julia = ["bread", "cheese", "bread"]

In [34]:
kaylie = julia

In [35]:
julia [1] = "tomato"

In [36]:
julia

['bread', 'tomato', 'bread']

In [37]:
kaylie

['bread', 'tomato', 'bread']

In [38]:
julia = "cheese sandwich"

In [39]:
julia

'cheese sandwich'

In [40]:
kaylie = julia

In [41]:
kaylie

'cheese sandwich'

In [42]:
julia = "tomato sandwich"

In [43]:
julia

'tomato sandwich'

In [44]:
kaylie

'cheese sandwich'

In [45]:
a = 1
a

1

In [46]:
b = a
b

1

In [47]:
a = 2
a

2

In [48]:
b

1

In [49]:
a = [1, 2]
a

[1, 2]

In [50]:
b = a
b

[1, 2]

In [51]:
a[0] = 6
a

[6, 2]

In [52]:
b

[6, 2]

In [53]:
combo = ["burger", "fries", "drink"]
kid_meal = list (combo) # making an independent copy of list

In [54]:
combo

['burger', 'fries', 'drink']

In [55]:
kid_meal

['burger', 'fries', 'drink']

In [56]:
combo[0] = "chicken sandwich"

In [58]:
combo

['chicken sandwich', 'fries', 'drink']

In [60]:
kid_meal

['burger', 'fries', 'drink']

In [62]:
perfect_sqaure

[1, 4, 9, 16, 25, 36, 49]

In [64]:
len(perfect_sqaure)

7

In [65]:
max (perfect_sqaure)

49

In [67]:
sum (perfect_sqaure)

140

In [68]:
letters = ["a", "b", "c"]
numbers = [1, 2, 3]
characters = letters + numbers
characters

['a', 'b', 'c', 1, 2, 3]

In [69]:
letters * 2

['a', 'b', 'c', 'a', 'b', 'c']

In [70]:
numbers * 2

[1, 2, 3, 1, 2, 3]

In [71]:
rainbow = ["red", "orange", "yellow", "green", "light blue", "blue", "violet"]
rainbow

['red', 'orange', 'yellow', 'green', 'light blue', 'blue', 'violet']

In [ ]:
rainbow.append("purple") 
# .append() method is used to add a single element to the end of the list
# take one argument with is the element to be added to the list

In [73]:
rainbow

['red', 'orange', 'yellow', 'green', 'light blue', 'blue', 'violet', 'purple']

In [74]:
rainbow.append (["purple"])

In [75]:
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'light blue',
 'blue',
 'violet',
 'purple',
 ['purple']]

In [ ]:
# .extend() method is to add elements from an iterable to the end of a list
# take one argument which is an iterable
# unpack the elements of the ietebale and add them one by one to the end of the original list
rainbow.extend("purple")

In [79]:
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'light blue',
 'blue',
 'violet',
 'purple',
 ['purple'],
 'p',
 'u',
 'r',
 'p',
 'l',
 'e']

In [90]:
rainbow.clear ()

In [91]:
rainbow

[]

In [92]:
fruits = ["pinapple", "apple", "kiwi", "banana"]
fruits

['pinapple', 'apple', 'kiwi', 'banana']

In [ ]:
# .sort()method 
fruits.sort()

In [94]:
fruits

['apple', 'banana', 'kiwi', 'pinapple']

In [95]:
# sorted() function
veggies = ["potato", "cabbage", "cabbage", "bell pepper", "onion"]
veggies

['potato', 'cabbage', 'cabbage', 'bell pepper', 'onion']

In [96]:
sorted (veggies)

['bell pepper', 'cabbage', 'cabbage', 'onion', 'potato']

In [97]:
veggies

['potato', 'cabbage', 'cabbage', 'bell pepper', 'onion']

In [ ]:
# tuple
# immutable (cannot be changed once it is created)
# ordered (the sequence or arrangement of the elements within the collection is maintained)
mutable_synonyms = ("chagneable", "fluctuating", "inconstant", "variable")
mutable_synonyms

('chagneable', 'fluctuating', 'inconstant', 'variable')

In [101]:
empty_tuple = ()
empty_tuple

()

In [102]:
also_empty = tuple ()
also_empty

()

In [ ]:
empty_tuple.append ("hi")
# because this is unchangeable, so you cannot use any method that change the original list

AttributeError: 'tuple' object has no attribute 'append'

In [106]:
len (mutable_synonyms)

4

In [107]:
sorted(mutable_synonyms)

['chagneable', 'fluctuating', 'inconstant', 'variable']

In [108]:
# set 
# mutable 
# unordered -> elements do not maintain any specific order
# distinct -> all elements are unique
things = {"coat", "lock", "box", "book", "apple", "hair", "lock", "book"}
things

{'apple', 'book', 'box', 'coat', 'hair', 'lock'}

In [109]:
visitor_post_code = ["M5R", "M5V", "M1M", "M1M", "M1T"]
visitor_post_code

['M5R', 'M5V', 'M1M', 'M1M', 'M1T']

In [110]:
set (visitor_post_code)

{'M1M', 'M1T', 'M5R', 'M5V'}

In [ ]:
empty_set = set () # the only way to create a empty set is to use set()
empty_set

set()

In [112]:
things

{'apple', 'book', 'box', 'coat', 'hair', 'lock'}

In [113]:
things.add("lock")

In [ ]:
things #things is not added because it is already there before

{'apple', 'book', 'box', 'coat', 'hair', 'lock'}

In [115]:
things.add("mirror")

In [116]:
things

{'apple', 'book', 'box', 'coat', 'hair', 'lock', 'mirror'}

In [117]:
things.remove("apple")

In [118]:
things

{'book', 'box', 'coat', 'hair', 'lock', 'mirror'}

In [119]:
rainbow = {"red", "orange", "yellow", "green", "blue", "indigo", "violet"}
olympic_flag = {"red", "green", "yellow", "blue", "black"}

In [ ]:
# doff: find the value in the first set that are not in the second set
rainbow.difference(olympic_flag)

{'indigo', 'orange', 'violet'}

In [122]:
# symetric diff: find the value that are in only one of the two sets
rainbow.symmetric_difference(olympic_flag)

{'black', 'indigo', 'orange', 'violet'}

In [ ]:
# intersection: find the values the two sets are in common
rainbow.intersection(olympic_flag)

{'blue', 'green', 'red', 'yellow'}

In [124]:
# union: combine the two sets to get the unique values in both
rainbow.union(olympic_flag)

{'black', 'blue', 'green', 'indigo', 'orange', 'red', 'violet', 'yellow'}

03/16/2026 Note below

In [ ]:
# Review from last week
list_example = [1, 3, 5, 7]
list_example
tuple_example = ("changeable", "flucuation", "inconstant")
tuple_example
set_example = {"coat", "lock", "box", "book", "book"}
set_example

In [ ]:
#dictionary
#mutable
#ordered

#key:value
#keys -> any immutable data type (Strings, numbers, booleans, tuples)
#values -> any data type

capitals = {"canada": "Ottawa",
            "United States": "Washington, D.C.",
            "Mexico": "Mecico City"}
capitals
olympic_cites = {2020: "Tokyo",
                 2016: "Rio De Janiero",
                 2012: "London"}
olympic_cites
all_olympic_hosts = {"summer": olympic_cites, 
                     "winter":{2020: "Beijing", 2018: "Pyeongchang", }}
all_olympic_hosts
empty_dictionary1 = {}
empty_dictionary1
empty_dictionary2 = dict()
empty_dictionary2
olympic_cites[2016]
all_olympic_hosts["summer"]
all_olympic_hosts["summer"][2016]
olympic_cites[2014]
# you will get an error if key is not found in the dictinoary with this function
# value = my_dict.get(key, default=None <if the key is not found in the dictionary>) method
olympic_cites.get(2014)
olympic_cites.get(2004, "Athens")
#if we assign a value to a key does not exist, the key: value pair will be added
olympic_cites[2008] = "Barcelona"
olympic_cites
#if we assign a value to a key already exist, the key: value pair will be updated
olympic_cites[2008] = "Beijing"
olympic_cites
# dictionary are mutable 
# updating a dictionary will also change other variablees that reference it
all_olympic_hosts
del olympic_cites[2020]
olympic_cites
all_olympic_hosts.keys()
olympic_cites.values()
all_olympic_hosts["winter"]
all_olympic_hosts["winter"].items()

In [ ]:
# for loop
vowels = ['a','e','i','o','u']
for i in vowels: # i = "a"
    print(i) # print ("a") and repeat

veggies = ['carrot', 'tomato', 'potato']
for vegatable in veggies:
    if vegatable == 'tomato':
        veggies[1] = 'turnip'
print(veggies)


# enumerate() function in Python is used to iterate over a sequence (e.g. list, tuple, string)
# while keeping track of the index position of each item
veggies = ['carrot', 'tomato', 'potato']

for idx,vegetable in enumerate(veggies):
    if vegatable == 'tomato':
        veggies[idx] = 'turnip'
print(veggies)
# for range() function which creates an iterable to loop over
for i in range(7):
    print(i, i*2)
input_files = ['data_01.csv', 'data_02.csv', 'data_03.csv', 'data_04.csv']
output_files = []

for i in input_files:
    output_files_name = 'processed_' + i.replace('csv', 'xlsx')
    output_files.append(output_files_name)

output_files
numbers = [1, 10, 100, 1000]
for idx, val in enumerate(numbers):
    numbers[idx] = val * 2

numbers

# loop over more than one iterable at the same time
lats = (43.56, 567.234, 23.5)
lons = (13.356, 2344.4, 34.7)

for i, j in zip(lats, lons):
    print (i,j)

In [17]:
# while loop
countdown = 4
while countdown > 0:
    print(countdown)
    countdown -= 1

4
3
2
1


In [ ]:
# break statements
# interrupts the execution of a loop

countdown =4

while countdown > 0:
    print(countdown)
    if countdown == 3:
        print('We are breaking the loop early')
        break
    countdown -= 1

print('Done iterating,')

4
3
We are breaking the loop early
Done iterating,


In [ ]:
while True: # if you do not put an break, this is infinite loop
    password = input('What is the password?')
    if password == 'open sesame':
        print('You\'re in!')
        break

You're in!


In [21]:
# continue statement 
# tells Python to leave the current iretation of the loop and start back up at the top

wishes = 3

while wishes > 0:
    wish = input('Make a wish:')
    if wish == 'infinite wishes':
        print('You can\'t do that!')
        continue
    else:
        print('Wish granted')
    wishes -= 1

print('You have used all your wishes.')

You can't do that!
Wish granted
Wish granted
You can't do that!
Wish granted
You have used all your wishes.


In [38]:
# with() ensures the files is properly closed after its suite(block of code) finished execution
# open() function return a file object, representation of the opened file
# .read() return the full file contents
# .readline()function return only the next linein the file (Python will keep track of where it is in the file)
# .readlines() function return the full file as a list, each item is one line in the file

with open('/Users/springzhou/DSI/python/05_src/data/slides_data/california_housing_test.csv', 'r') as file:
    print(file.readline())
    print(file.readline())

"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"

-122.050000,37.370000,27.000000,3885.000000,661.000000,1537.000000,606.000000,6.608500,344700.000000



03/18/2026 Notes Below

## Opening, Reading, and Writing Files

Python has a built-in function, `open()` for opening files. `open()` takes a string indicating the _file path_, or location, of the file to open, plus a one-character string indicating whether we should open the file in read-only, overwrite, or append mode.

| `open()` mode | Description |
|---|---|
|`'r'` | Read-only. Produces an error if the file does not already exist. |
|`'w'` | Write. Creates a new file if one does not exist. If the file already exists, the current contents are deleted and overwritten. |
|`'a'`| Append. Adds to an existing file. If the file does not exist, it will be created. |

In [ ]:
# .write() write a string to a file 
# .writelines() write each item in an iterable to a file, with no seperating text in between

provinces = ['BC', 'AB', 'SK', 'MB', 'ON', 'QC', 'NL', 'NB', 'NS', 'PEI']
with open('provinces.txt', 'w') as province_file: # or Users/springzhou/DSI/python/provinces.txt
    province_file.writelines(provinces)

In [2]:
with open('provinces.txt', 'r') as province_file:
    print(province_file.read())

BCABSKMBONQCNLNBNSPEI


In [ ]:
import os #os is a library

In [ ]:
os.getcwd() #help you to get the current directory

'/Users/springzhou/DSI/python'

In [5]:
os.listdir()

['03',
 '05_src',
 'provinces.txt',
 '.DS_Store',
 'LICENSE',
 'uv.lock',
 'python-env',
 'SETUP.md',
 'pyproject.toml',
 '01_materials',
 'README.md',
 '04_this_cohort',
 '02_activities',
 '03_instructional_team',
 '.gitignore',
 'steps_to_ask_for_help.png',
 '.github',
 'SpringZ.ipynb',
 '.git']

In [6]:
cwd = os.getcwd()
full_paths = []
for i in os.listdir():
    full_paths.append(os.path.join(cwd, i))
full_paths

['/Users/springzhou/DSI/python/03',
 '/Users/springzhou/DSI/python/05_src',
 '/Users/springzhou/DSI/python/provinces.txt',
 '/Users/springzhou/DSI/python/.DS_Store',
 '/Users/springzhou/DSI/python/LICENSE',
 '/Users/springzhou/DSI/python/uv.lock',
 '/Users/springzhou/DSI/python/python-env',
 '/Users/springzhou/DSI/python/SETUP.md',
 '/Users/springzhou/DSI/python/pyproject.toml',
 '/Users/springzhou/DSI/python/01_materials',
 '/Users/springzhou/DSI/python/README.md',
 '/Users/springzhou/DSI/python/04_this_cohort',
 '/Users/springzhou/DSI/python/02_activities',
 '/Users/springzhou/DSI/python/03_instructional_team',
 '/Users/springzhou/DSI/python/.gitignore',
 '/Users/springzhou/DSI/python/steps_to_ask_for_help.png',
 '/Users/springzhou/DSI/python/.github',
 '/Users/springzhou/DSI/python/SpringZ.ipynb',
 '/Users/springzhou/DSI/python/.git']

In [ ]:
# check if a file exists to avoid overwriting it
text = 'Lavender is a small purple flower.'

if os.path.exists('plants.txt'):
    print('plants.txt already exists')
else:
    with open('plants.txt', 'w') as f:
        f.write(text)

plants.txt already exists


In [29]:
# class: blueprint or template for creating objects
# define the proprities (attubutes) and behaviours (methods) that objects of that class will have user-defined data type

# objects: specific instance of a class
# have (attubutes) and behaviours (methods) 

# method: function that is associated with a class and can be called on objects of that class
# behaviour of the object

# attribut: pieces of data that belong to an object
# represnt state of the object

#kcar_name = "Ketchup"
##kcar_make = "Volkswagon"
#kcar_model = "UP!"
#kcar_color = "Red"

#dcar_name = "Taylor"
#dcar_make = "Honda"
#dcar_model = "Civic"
#dcar_color = "Black"

class Car:  # start with uppercase
    def __init__(self, name, make, model, color): #two underscore
        self.name = name
        self.make = make
        self.model = model
        self.color = color
    def honk(self):
        print("beep beep")

In [30]:
kcar = Car("Ketchup", "Volkswagon", "UP!", "Red")
dcar = Car("Taylor", "Honda", "Civic", "Black")

In [27]:
kcar.color

'Red'

In [28]:
dcar.honk()

beep beep


In [31]:
kcar.make

'Volkswagon'

In [19]:
# __init__ special method in Python classes
# automactically called when a new object of a class is created
# used to initilize the object's attributes

# self is a reference to the current instance of the class
# first parameter in every method defination inside a class

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def greet(self):
        print ("hello, my name is ", self.name)

In [20]:
spring = Person("Spring", 1000)

In [21]:
spring.name

'Spring'

In [22]:
spring.greet()

hello, my name is  Spring


## Arrays vs lists

| `numpy` arrays | Python `list` |
|---|---|
| all elements must be the same type | elements can be different types |
| fixed size | can change size |
| n-dimensional | 1-dimensional |
| faster to process | slower to process |
| consumes less memory | consumes more memory |

In [32]:
import numpy as np

In [ ]:
# first axis(row) is 2
# second axis (columns) is 3
# 2 X 3 array

a = np.array([[1, 2, 3],
              [3, 2, 1]])
a

array([[1, 2, 3],
       [3, 2, 1]])

In [ ]:
a.ndim #number of dimensions

2

In [ ]:
# notice that the shape is rows x columns
a.shape

(2, 3)

In [ ]:
# notice that the size is rows * columns
a.size

6

In [ ]:
# datatype inside of the array 
a.dtype

dtype('int64')

In [ ]:
np.zeros((2, 3, 2)) # 2 X 3 X 2 dimension of zeros #()because you put tuple here

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones_like(a) # 2X3 array of ones just the a you already generate before

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [42]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.random.randint(1, 10, (3, 4)) # everytime you execute, the numbers are different(random)

array([[3, 5, 6, 7],
       [1, 1, 1, 2],
       [3, 9, 5, 5]])

In [ ]:
np.random.seed(1) # the numbers will not change, you generate a reproducable set of number
np.random.randint(1, 10, (3, 4))

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3]])

In [ ]:
np.repeat(10, 5) #repeat the first number 10 for 5 times

array([10, 10, 10, 10, 10])

In [51]:
onedim_arr = np.array ([1, 2, 3, 4, 5])
multidim_arr = np.repeat(onedim_arr, 5)
multidim_arr

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [52]:
multidim_arr = np.tile(onedim_arr, (5, 1))
multidim_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [54]:
another_arr = np.tile(onedim_arr, (3,3))
another_arr

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [55]:
b = np.array([[5, 4, 3, 2, 1, 0], [10, 8, 6, 4, 2, 0]])

b.T

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [ ]:
b #size is 12

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [ ]:
b.reshape (4, 3) # you need to make sure the size of array are match 

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [58]:
b.flatten()

array([ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0])

In [59]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [60]:
b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [61]:
np.hstack((b, a))

array([[ 5,  4,  3,  2,  1,  0,  1,  2,  3],
       [10,  8,  6,  4,  2,  0,  3,  2,  1]])

In [62]:
np.vstack((b.reshape(4,3), a))

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0],
       [ 1,  2,  3],
       [ 3,  2,  1]])

In [64]:
arr1 = np.array ([5, 10, 15, 20])
arr1

array([ 5, 10, 15, 20])

In [65]:
arr2 = np.arange(5, 9)
arr2

array([5, 6, 7, 8])

In [66]:
arr1 - arr2

array([ 0,  4,  8, 12])

In [67]:
arr1 * 2

array([10, 20, 30, 40])

In [ ]:
arr2 + np.array([1, 2]) # you could not add array without the same size

In [68]:
print(arr1.sum())

50


In [69]:
print(arr1.max())

20


In [71]:
print(arr1.mean())

12.5


In [72]:
print(np.median(arr1))

12.5


In [73]:
tens = np.arange(0, 120, 10).reshape(3, 4)

In [74]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [76]:
horizontal = np.array([-5, -10, -15, -20])
horizontal



array([ -5, -10, -15, -20])

In [77]:
tens + horizontal

array([[-5,  0,  5, 10],
       [35, 40, 45, 50],
       [75, 80, 85, 90]])

In [78]:
vertical = np.array([[100],
                     [200],
                     [300]])
vertical

array([[100],
       [200],
       [300]])

In [79]:
tens + vertical

array([[100, 110, 120, 130],
       [240, 250, 260, 270],
       [380, 390, 400, 410]])

In [80]:
# axis = 0 column-wise operation(going down the rows)
# axis = 1 row-wise operation (across the columns)
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [81]:
tens.mean(axis=0)

array([40., 50., 60., 70.])

In [82]:
tens.mean(axis=1)

array([15., 55., 95.])

In [83]:
arr1

array([ 5, 10, 15, 20])

In [84]:
arr1[1]

np.int64(10)

In [85]:
arr1[1:3]

array([10, 15])

In [86]:
for i in arr1:
    print(i)

5
10
15
20


In [ ]:
tens[1, 2] #for multi-dimension, you need to indicate each dimension

np.int64(60)

In [88]:
tens[1]

array([40, 50, 60, 70])

In [ ]:
tens[:,0] #:means nothing on the row

array([ 0, 40, 80])

In [91]:
tens[0:2, 1:3]

array([[10, 20],
       [50, 60]])

In [92]:
matrix1 = np.random.randint(1, 11, 12).reshape(3, 4)
matrix2 = matrix1

# indepedent copy
matrix3 = matrix1.copy()

In [93]:
matrix1

array([[ 5,  3,  5,  8],
       [ 8, 10,  2,  8],
       [ 1,  7, 10, 10]])

In [94]:
matrix1[1] = [0, 0, 0, 0]

In [95]:
matrix1

array([[ 5,  3,  5,  8],
       [ 0,  0,  0,  0],
       [ 1,  7, 10, 10]])

In [ ]:
matrix2 #matrix2 also updated because we change matrix1

array([[ 5,  3,  5,  8],
       [ 0,  0,  0,  0],
       [ 1,  7, 10, 10]])

In [97]:
matrix3

array([[ 5,  3,  5,  8],
       [ 8, 10,  2,  8],
       [ 1,  7, 10, 10]])